%YAML:1.0

# 1: realtime, 0: non-realtime
test.RealTime: 0
# Time for visual-inertial initialization
test.VINSInitTime: 15.0 #15

# Modify test.InitVIOTmpPath and bagfile to the correct path
# Path to save tmp files/results
test.InitVIOTmpPath: "/home/hmx/opensourcecode/OpenSourceORBVIO/tmp/"

## For good initialization (no movement at the beginning for some bag)
test.DiscardTime: 0

imufile: "/home/hmx/LearnVIORB/Data/b2904_5/b2904_5/IMU_vol_XYZ_2_b2904_5.txt"
timefile: "/home/hmx/LearnVIORB/Data/pro/imageNum.txt"

#######################################
PNPMODE: 1
DatasetSource: 3
# 0:ADSC
# 1:KITTY 
# 2:EuRoC
# 3:Kagaru Airborne Dataset

nphoto1: 1
nphoto2: 10396
imagefile: "/home/hmx/RepairORB/Data/Kagaru Airborne Dataset/cam0_image"


#######################################
#bagfile: "/home/jp/TimeV1_01_easy.bag"
imutopic: "/imu0"
imagetopic: "/cam0/image_raw"


# Timestamp shift. Timage = Timu + image_delay
Camera.delaytoimu: 0

# acc=acc*9.8, if below is 1
IMU.multiplyG: 0

# camera-imu frame transformation, Pi = Tic * Pc
Camera.Tbc:
   [-1.0, 0.0, 0.0, 0.0,
  0.0, 1.0, 0.0, 0.0,
  0.0, 0.0, -1.0, 0.0,
  0.0, 0.0, 0.0, 1.0]


# Local Window size
LocalMapping.LocalWindowSize: 20


#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
#1646.07299, 1645.39302 620.74483, 477.47527 -0.20465, 0.18856, -0.00111, 0.00040, 0.00000

Camera.fx: 1646.07299 #1641.99751 
Camera.fy: 1645.39302 #1642.30964 
Camera.cx: 620.74483 #642.15139
Camera.cy: 477.47527 #470.34929

Camera.k1: -0.20465 #-0.19978
Camera.k2: 0.18856 #0.13511
Camera.p1: -0.00111 #-0.00007
Camera.p2: 0.00040 #-0.00005
Camera.k3: 0.00000

Camera.width: 1280
Camera.height: 960

# Camera frames per second 
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 0

# Close/Far threshold. Baseline times.
ThDepth: 40.0

# Deptmap values factor
DepthMapFactor: 1.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.1
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 1
Viewer.PointSize: 2
Viewer.CameraSize: 0.15
Viewer.CameraLineWidth: 2
Viewer.ViewpointX: 0
Viewer.ViewpointY: -10
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000

